blog/urls.py
from django.urls import path,re_path
from blog import views


app_name = 'blog'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    re_path('^post/(?P<pk>[0-9]+)/', views.PostDetailView.as_view(), name='detail'),
    re_path('^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/', views.ArchivesView.as_view(), name='archives'),
    re_path('^category/(?P<pk>[0-9]+)/', views.CategoryView.as_view(), name='category'),
    re_path('^tag/(?P<pk>[0-9]+)/', views.TagView.as_view(), name='tag'),


    # path('',views.index,name = 'index'),
    # re_path('post/(?P<pk>[0-9]+)/',views.detail,name='detail'),
    # (?P<name>…)带命名的组
    # [0-9]+表示一位或者多位数. (?P<pk>[0-9]+)表示命名捕获组, 其作用是从用户访问的URL里把括号内匹配的字符串捕获并作为关键字参数传给其对应的视图函数 detail
    # re_path('archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/',views.arhchives, name='archives'),
    # re_path('category/(?P<pk>[0-9]+)/', views.category, name='category'),

]

try_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('', include('comments.urls')),

    path('all/rss/', AllPostsRssFeed(), name='rss'),

    path('search/', include('haystack.urls')),

]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Try Blog</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    {#    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">#}
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <!-- for highlight -->
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <style>
        span.highlighted {
            color: pink;
        }
    </style>

    <!-- js -->
    {#    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>#}
    {#    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>#}
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    {#  <h1><a href="/index/"><b>Try</b> _ blog</a></h1>#}
                    <h1><a href="{% url 'blog:index' %}"><b>Try</b> _ Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="Index">Index</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="CV">CV</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>


<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}


                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_post as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            暂无文章！
                        {% endfor %}
                    </ul>

                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">Archive</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                {#                            href="/archives/{{ date.year }}/{{ date.month }}"/ #}
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}
                                    年 {{ date.month }} 月</a>
                            </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span
                                        class="post-count">({{ category.num_posts }})</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
{#    {% block tags %}#}
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签s</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                            </li>
                        {% empty %}
                            暂无标签！
                        {% endfor %}
                    </ul>
                </div>
{#    {% endblock tags %}#}

                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS Subscribe </a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 - <a href="#" target="_blank">Charon111</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">Index</a></li>
            <li><a href="full-width.html">Blog</a></li>
            <li><a href="about.html">CV</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>